# Generated by Django 3.2.3 on 2021-05-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftsystem', '0010_alter_basetoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetoken',
            name='tokenId',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
